### PR TITLE
fix: print extra entries for failed interactions

### LINKED ISSUE #25: Extra entries from failed interactions are not printed
Only the missing entries are printed.

This can lead to a situation like this :

image

### PR DESCRIPTION
**Pull request by GuillaumeVoisine**
## Description

Add outputs for extra entries.

image

## Related issues

closes #25 

## Checklist

- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guidelines 
- [x] All relevant PR sections are populated, irrelevant ones are removed

### CODE REVIEW

**Comment by NetBKarine** [comment]
T'as pas un screenshot par hasard, histoire de prouver que ça marche ton affaire?

**Comment by GuillaumeVoisine** [comment]
Voir le screenshot rajouté dans la description du PR.

**Review by NetBKarine — CHANGES_REQUESTED** [review]
It's good but not so clear. Highlighting extra elements and absent one with different colors would be very useful (in another version, we use green for extra and red for missing)

**Comment by GuillaumeVoisine** [comment]
https://files.slack.com/files-pri/T02KPMGS3-F01EHV5TQEN/image.png

**Pull request merged**
